python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 0
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 1
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 2
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 3
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 4
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 5
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 6
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 7
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 8
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 9
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 10
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 11
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 12
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 13
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 14
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 15
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 16
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 17
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 18
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 19
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 20
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 21
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 22
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 23
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 24
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 25
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 26
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 27
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_29 28
