python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 0
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 1
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 2
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 3
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 4
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 5
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 6
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 7
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 8
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 9
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 10
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 11
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 12
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 13
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 14
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 15
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 16
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 17
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 18
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 19
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 20
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 21
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 22
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 23
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 24
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 25
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 26
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 27
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 28
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 29
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 30
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 31
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 32
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 33
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 34
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 35
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 36
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 37
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 38
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 39
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 40
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 41
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 42
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 43
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 44
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 45
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 46
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 47
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 48
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 49
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 50
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 51
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 52
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 53
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 54
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 55
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 56
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 57
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 58
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_60 59
