python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 0
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 1
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 2
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 3
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 4
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 5
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 6
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 7
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 8
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 9
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 10
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 11
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 12
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 13
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 14
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 15
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 16
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 17
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 18
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 19
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 20
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 21
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 22
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 23
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 24
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 25
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 26
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 27
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 28
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 29
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 30
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 31
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 32
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 33
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 34
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 35
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 36
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 37
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 38
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 39
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 40
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 41
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 42
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 43
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 44
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 45
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 46
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 47
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 48
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 49
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 50
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 51
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 52
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 53
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 54
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 55
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 56
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 57
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 58
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 59
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 60
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 61
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 62
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 63
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 64
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 65
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 66
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 67
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 68
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 69
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 70
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 71
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 72
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 73
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 74
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 75
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 76
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 77
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 78
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 79
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 80
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 81
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 82
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 83
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 84
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 85
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 86
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 87
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 88
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 89
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 90
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 91
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 92
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 93
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 94
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 95
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 96
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 97
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 98
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 99
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 100
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 101
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 102
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 103
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 104
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 105
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 106
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 107
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 108
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 109
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 110
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 111
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 112
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 113
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 114
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 115
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 116
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 117
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 118
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 119
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 120
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 121
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 122
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 123
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 124
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 125
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 126
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 127
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 128
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py cogatlas_lda_130 129
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 0
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 1
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 2
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 3
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 4
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 5
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 6
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 7
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 8
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 9
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 10
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 11
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 12
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 13
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 14
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 15
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 16
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 17
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 18
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 19
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 20
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 21
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 22
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 23
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 24
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 25
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 26
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 27
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 28
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 29
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 30
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 31
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 32
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 33
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 34
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 35
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 36
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 37
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 38
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 39
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 40
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 41
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 42
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 43
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 44
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 45
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 46
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 47
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 48
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 49
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 50
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 51
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 52
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 53
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 54
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 55
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 56
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 57
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 58
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 59
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 60
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 61
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 62
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 63
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 64
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 65
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 66
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 67
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 68
python /work/01329/poldrack/code/poldrack/textmining/paper/utils/mk_chisq_maps_filter.py disorders_lda_70 69
